config/routes.rb
Rails.application.routes.draw do
  
  resources :activities

  root to: 'employees#index'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  resources :nominations, only: [:index]

  resources :employees do
    resources :nominations
  end

end

app/models/employee.rb
class Employee < ActiveRecord::Base
  extend FriendlyId
  friendly_id :full_name, use: :slugged

  has_many :nominations

  mount_uploader :employee_image, EmployeeUploader

  before_destroy :destroy_nominations

  def as_json(options={})
    if count_by_employee != 0
      super(:only => [:fname,:lname,:id],
        :methods => [:count_by_employee,:full_name]
        )
    else
      super(:only => [:fname,:lname,:id])
    end
  end

  def count_by_employee
    @count_by_employee = Nomination.where(employee_id: id, :created_at => '2016-11-02'.to_date.beginning_of_day..Time.now).count

  end 


  def full_name
    "#{fname} #{lname}"
  end

  private
  
    def destroy_nominations
     self.nominations.delete_all   
    end
  
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]
  before_filter :authorize, only: [:edit, :update, :destroy, :create, :new]

  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.order(:lname)
    respond_to do |format|
      format.json { render json: @employees }
      format.html { @employees }
    end
  end

  def count
    @employees = Employee.all
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
    @employee = Employee.friendly.find(params[:id])
    @nomination = Nomination.new
    @nominations = @employee.nominations
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee = Employee.friendly.find(params[:id])
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url, notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params[:employee].permit(:fname, :lname, :employee_image, :slug)
    end

end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_form.html.erb
<%= form_for(@employee) do |f| %>
  <% if @employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% @employee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :fname %><br>
    <%= f.text_field :fname %>
  </div>
  <div class="field">
    <%= f.label :lname %><br>
    <%= f.text_field :lname %>
  </div>
  <div class="field">
    <%= f.label :employee_image %><br>
    <%= f.file_field :employee_image %>
  </div>
  <div class="actions">
    <%= f.submit 'Create Employee', :class => 'btn btn-primary' %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Editing employee</h1>

<%= render 'form' %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
<% @employees.each_slice(4) do |slice| %>
  <div class="row" style="margin-bottom: 30px">
    <% slice.each do |employee| %>
      <div class="col-md-3">
        <%= link_to employee  do %>
          <div class="employee-bg" style="background-image: url(<%= employee.employee_image.to_s %>); height: 300px">
            <div class="name-bar">
                <div class="text-center employee-name">
                  <%= employee.full_name %>
                </div>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/employees/new.html.erb
<h1>New employee</h1>

<%= render 'form' %>

<%= link_to 'Back', employees_path %>

app/views/employees/show.html.erb
<div class="row">
  <h2 class="text-center"><%= @employee.full_name %></h2>
</div>

<div class="row">
  <div class="col-md-4 col-md-offset-4 text-center">
    <%= image_tag @employee.employee_image.thumb.to_s %>
  </div>
</div>

<div class="row">
  <div class="col-md-4 col-md-offset-4">
    
    <%= render 'nominations/form' %>

    <% if signed_in? %>
        <%= link_to "Edit", edit_employee_path, :class => 'btn btn-primary form-control' %>
        <%= link_to "Delete", @employee, method: :delete, :class => 'btn btn-danger form-control top-margin-10' %>
        <%= %>
      <% end %>
  </div>
</div>
<div class="row">
  <hr />
</div>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Reason</th>
          <th>Nominator</th>
        </tr>
      </thead>

      <tbody>
      <% @nominations.each do |nomination| %>
        <tr>
          <td><%= nomination.reason %></td>
          <td><%= nomination.nominator %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

<%= link_to 'Back', employees_path %>