config/routes.rb
Rails.application.routes.draw do
  
  resources :activities

  root to: 'employees#index'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  resources :nominations, only: [:index]

  resources :employees do
    resources :nominations
  end

end

app/models/activity.rb
class Activity < ActiveRecord::Base

  def as_json(options={})
    super(:only => [:title,:name,:date],
      :methods => [:current],
      )
  end

  def current
    @activities = Activity.where(:created_at => '2016-05-16'.to_date.beginning_of_day..Time.now).reverse
    respond_to do |format|
      format.json { render json: @activities }
      format.html { @activities }
    end
  end
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :set_activity, only: [:show, :edit, :update, :destroy]
  before_filter :authorize, only: [:create, :new, :edit, :update, :destroy]

  # GET /activities
  # GET /activities.json
  def index
    @activities = Activity.where('date > ?', Date.today).reverse
        @nominations = Nomination.where(:created_at => '2016-05-16'.to_date.beginning_of_day..Time.now).reverse

  end

  # GET /activities/1
  # GET /activities/1.json
  def show
  end

  # GET /activities/new
  def new
    @activity = Activity.new
  end

  # GET /activities/1/edit
  def edit
  end

  # POST /activities
  # POST /activities.json
  def create
    @activity = Activity.new(activity_params)

    respond_to do |format|
      if @activity.save
        format.html { redirect_to @activity, notice: 'Activity was successfully created.' }
        format.json { render :show, status: :created, location: @activity }
      else
        format.html { render :new }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activities/1
  # PATCH/PUT /activities/1.json
  def update
    respond_to do |format|
      if @activity.update(activity_params)
        format.html { redirect_to @activity, notice: 'Activity was successfully updated.' }
        format.json { render :show, status: :ok, location: @activity }
      else
        format.html { render :edit }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1
  # DELETE /activities/1.json
  def destroy
    @activity.destroy
    respond_to do |format|
      format.html { redirect_to activities_url, notice: 'Activity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activity
      @activity = Activity.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def activity_params
      params.require(:activity).permit(:title, :name, :date)
    end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/views/activities/_form.html.haml
= form_for @activity do |f|
  - if @activity.errors.any?
    #error_explanation
      %h2= "#{pluralize(@activity.errors.count, "error")} prohibited this activity from being saved:"
      %ul
        - @activity.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :date
    = f.date_select :date
  .actions
    = f.submit 'Save'

app/views/activities/current.html.haml
%h1 Current activities

%table
  %tr
    %th Title
    %th Name
    %th Date
    %th
    %th
    %th

  - @activities.current.each do |activity|
    %tr
      %td= activity.title
      %td= activity.name
      %td= activity.date
      %td= link_to 'Show', activity
      %td= link_to 'Edit', edit_activity_path(activity)
      %td= link_to 'Destroy', activity, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Activity', new_activity_path

app/views/activities/edit.html.haml
%h1 Editing activity

= render 'form'

= link_to 'Show', @activity
\|
= link_to 'Back', activities_path

app/views/activities/index.html.haml
%h1 Listing activities

%table
  %tr
    %th Title
    %th Name
    %th Date
    %th
    %th
    %th

  - @activities.each do |activity|
    %tr
      %td= activity.title
      %td= activity.name
      %td= activity.date
      %td= link_to 'Show', activity
      %td= link_to 'Edit', edit_activity_path(activity)
      %td= link_to 'Destroy', activity, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Activity', new_activity_path

app/views/activities/new.html.haml
%h1 New activity

= render 'form'

= link_to 'Back', activities_path

app/views/activities/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @activity.title
%p
  %b Name:
  = @activity.name
%p
  %b Date:
  = @activity.date

= link_to 'Edit', edit_activity_path(@activity)
\|
= link_to 'Back', activities_path