config/routes.rb
Rails.application.routes.draw do
  
  resources :activities

  root to: 'employees#index'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'

  resources :nominations, only: [:index]

  resources :employees do
    resources :nominations
  end

end

app/views/layouts/_header.html.erb
<div class="row"><h1 class="text-center"><%= link_to "Lightsaber Award", root_path %></h1></div>
<header class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
        <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Nominations", nominations_path %></li>
          <% if signed_in? %>
            <li><%= link_to "New Employee", new_employee_path %></li>
            <li><%= link_to "Activities", activities_path %></li>
            <li><%= link_to "Sign out", logout_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Recognizer </title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>
<div class = 'container'>
  <%= yield %>
</div>

</body>
</html>